// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package db

import (
	"context"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications(name,api_key)
VALUES($1,$2)
RETURNING id, name, api_key, created_at
`

type CreateApplicationParams struct {
	Name   string `json:"name"`
	ApiKey string `json:"api_key"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.Name, arg.ApiKey)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}
