// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO delivery_attempts (event_id, endpoint_id, status, http_status, attempt_number, next_retry_at, delivered_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_id, endpoint_id, status, http_status, attempt_number, next_retry_at, delivered_at, created_at
`

type CreateAttemptParams struct {
	EventID       int64              `json:"event_id"`
	EndpointID    int64              `json:"endpoint_id"`
	Status        string             `json:"status"`
	HttpStatus    pgtype.Int4        `json:"http_status"`
	AttemptNumber int32              `json:"attempt_number"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.EventID,
		arg.EndpointID,
		arg.Status,
		arg.HttpStatus,
		arg.AttemptNumber,
		arg.NextRetryAt,
		arg.DeliveredAt,
	)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.HttpStatus,
		&i.AttemptNumber,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAttemptsByEvent = `-- name: ListAttemptsByEvent :many
SELECT id, event_id, endpoint_id, status, http_status, attempt_number, next_retry_at, delivered_at, created_at FROM delivery_attempts
WHERE event_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAttemptsByEvent(ctx context.Context, eventID int64) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Status,
			&i.HttpStatus,
			&i.AttemptNumber,
			&i.NextRetryAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
