// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoints.sql

package db

import (
	"context"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (app_id, url, secret)
VALUES ($1, $2, $3)
RETURNING id, app_id, url, secret, is_active, created_at
`

type CreateEndpointParams struct {
	AppID  int64  `json:"app_id"`
	Url    string `json:"url"`
	Secret string `json:"secret"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint, arg.AppID, arg.Url, arg.Secret)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Url,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
UPDATE endpoints SET is_active = false
WHERE id = $1 AND app_id = $2
`

type DeleteEndpointParams struct {
	ID    int64 `json:"id"`
	AppID int64 `json:"app_id"`
}

func (q *Queries) DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, arg.ID, arg.AppID)
	return err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, app_id, url, secret, is_active, created_at FROM endpoints
WHERE id = $1
`

func (q *Queries) GetEndpointByID(ctx context.Context, id int64) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByID, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Url,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listEndpointsByApp = `-- name: ListEndpointsByApp :many
SELECT id, app_id, url, secret, is_active, created_at FROM endpoints
WHERE app_id = $1 AND is_active = true
`

func (q *Queries) ListEndpointsByApp(ctx context.Context, appID int64) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpointsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Url,
			&i.Secret,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
