// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (app_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, app_id, event_type, payload, created_at
`

type CreateEventParams struct {
	AppID     int64  `json:"app_id"`
	EventType string `json:"event_type"`
	Payload   []byte `json:"payload"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.AppID, arg.EventType, arg.Payload)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, app_id, event_type, payload, created_at FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsByApp = `-- name: ListEventsByApp :many
SELECT id, app_id, event_type, payload, created_at FROM events
WHERE app_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListEventsByApp(ctx context.Context, appID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
