// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	ApiKey    string             `json:"api_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
